import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { Clock3, Play, Square } from 'lucide-react';
import { hourlyApi } from '../api/hourly.js';
import { apiErrorMessage } from '../api/client.js';
export default function HourlyWork() {
  const { contractId } = useParams(); const [data, setData] = useState(null); const [error, setError] = useState(''); const [description, setDescription] = useState(''); const [busy, setBusy] = useState(false);
  const load = () => hourlyApi.summary(contractId).then(setData).catch((e) => setError(apiErrorMessage(e, 'Hourly workspace could not be loaded.')));
  useEffect(() => { load(); }, [contractId]);
  const start = async () => { setBusy(true); try { await hourlyApi.start(contractId); await load(); } catch (e) { setError(apiErrorMessage(e)); } finally { setBusy(false); } };
  const stop = async () => { setBusy(true); try { if (data?.activeTimer) { await hourlyApi.stop(data.activeTimer._id, { description: description || 'Tracked work' }); setDescription(''); await load(); } } catch (e) { setError(apiErrorMessage(e)); } finally { setBusy(false); } };
  if (!data) return <div className="p-8 text-slate-500">Loading time tracking...</div>;
  const rate = data.contract.hourlyRate ?? data.contract.rate ?? 0;
  return <section className="max-w-4xl"><p className="text-sm font-semibold uppercase tracking-wider text-brand-600">Hourly workspace</p><h1 className="mt-1 text-3xl font-bold text-slate-900">{data.contract.title}</h1><p className="mt-2 text-slate-500">Server-authoritative time tracking at ${rate}/hour. Your work description is included in the weekly review.</p>{error && <div className="mt-5 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>}<div className="mt-6 rounded-2xl bg-slate-900 p-6 text-white"><div className="flex items-center justify-between"><div><p className="text-sm text-slate-300">This workspace</p><p className="mt-1 text-3xl font-bold">{Math.floor((data.totalMinutes || 0) / 60)}h {(data.totalMinutes || 0) % 60}m</p><p className="text-sm text-slate-300">billable time recorded</p></div><Clock3 className="h-12 w-12 text-brand-300" /></div><div className="mt-5 flex flex-col gap-3 sm:flex-row">{data.activeTimer ? <><input className="min-w-0 flex-1 rounded-lg px-3 py-2 text-slate-900" value={description} onChange={(e) => setDescription(e.target.value)} placeholder="What are you working on?" /><button disabled={busy} onClick={stop} className="flex items-center justify-center gap-2 rounded-lg bg-red-500 px-4 py-2 font-semibold"><Square className="h-4 w-4" /> Stop timer</button></> : <button disabled={busy} onClick={start} className="flex items-center justify-center gap-2 rounded-lg bg-brand-500 px-4 py-2 font-semibold"><Play className="h-4 w-4" /> Start timer</button>}</div></div><div className="mt-6 rounded-xl border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5"><h2 className="font-semibold text-slate-900">Time entries</h2><p className="text-sm text-slate-500">Entries are rounded according to the contract settings.</p></div><div className="divide-y divide-slate-100">{data.entries?.length ? data.entries.map((e) => <div className="flex items-center justify-between gap-4 p-5" key={e._id}><div><p className="font-medium text-slate-900">{e.description}</p><p className="text-sm text-slate-500">{new Date(e.startedAt).toLocaleString()} · {e.source}</p></div><div className="text-right"><p className="font-semibold text-slate-900">{e.billableMinutes} min</p><p className="text-sm text-slate-500">${e.amount.toFixed(2)}</p></div></div>) : <p className="p-8 text-center text-slate-500">No time recorded yet.</p>}</div></div></section>;
}
