import { Link } from 'react-router-dom';
import { ArrowRight, Check, ClipboardList, Handshake, MessageCircle, Search, ShieldCheck, Sparkles } from 'lucide-react';
import { Button } from '../components/Button.jsx';

const clientSteps = [['01', 'Share the outcome', 'Post a clear brief with your goals, budget, and timeline.'], ['02', 'Meet the right people', 'Review proposals, compare experience, and use transparent match signals.'], ['03', 'Work with confidence', 'Message your freelancer, track milestones, and review the finished work.']];
const freelancerSteps = [['01', 'Show your strengths', 'Build a profile that makes your skills, experience, and work easy to understand.'], ['02', 'Find your fit', 'Discover relevant jobs or offer a focused service with a clear scope.'], ['03', 'Deliver great work', 'Collaborate, submit work for review, and build a reputation one project at a time.']];

function Path({ title, intro, steps, client }) { return <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div className="flex items-start justify-between gap-5"><div><span className="text-sm font-bold uppercase tracking-[0.2em] text-brand-600">For {client ? 'clients' : 'freelancers'}</span><h2 className="mt-3 text-2xl font-bold text-slate-900">{title}</h2><p className="mt-3 max-w-md text-slate-500">{intro}</p></div><div className="hidden rounded-2xl bg-slate-100 p-3 sm:block">{client ? <ClipboardList className="h-7 w-7 text-brand-600" /> : <Handshake className="h-7 w-7 text-brand-600" />}</div></div><div className="mt-8 space-y-6">{steps.map(([number, heading, text]) => <div className="flex gap-4" key={number}><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-brand-50 text-xs font-bold text-brand-700">{number}</span><div><h3 className="font-bold text-slate-900">{heading}</h3><p className="mt-1 text-sm leading-6 text-slate-500">{text}</p></div></div>)}</div></div>; }

export default function HowItWorks() { return <div><section className="bg-[#eaf7f6]"><div className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8 lg:py-28"><div className="max-w-3xl"><div className="inline-flex items-center gap-2 rounded-full bg-white px-3 py-1.5 text-sm font-semibold text-teal-700 shadow-sm"><Sparkles className="h-4 w-4" /> Work should feel clear</div><h1 className="mt-6 text-4xl font-bold tracking-tight text-slate-950 sm:text-6xl">Good work starts with a good match.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">TalentHive brings the brief, the people, and the progress into one thoughtful workspace, so both sides can do their best work.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/find-jobs"><Button size="lg">Find a job <ArrowRight className="h-4 w-4" /></Button></Link><Link to="/find-talent"><Button variant="secondary" size="lg">Find talent</Button></Link></div></div></div></section><section className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><div className="grid gap-5 lg:grid-cols-2"><Path client title="From brief to finished work" intro="Everything you need to hire thoughtfully and keep a project moving." steps={clientSteps} /><Path title="From profile to proud portfolio" intro="Find work that fits your strengths, then turn great delivery into lasting trust." steps={freelancerSteps} /></div></section><section className="bg-slate-950 text-white"><div className="mx-auto grid max-w-7xl gap-12 px-4 py-20 sm:px-6 lg:grid-cols-3 lg:px-8"><div><ShieldCheck className="h-8 w-8 text-cyan-300" /><h2 className="mt-5 text-2xl font-bold">Built for confidence</h2><p className="mt-3 text-sm leading-6 text-slate-300">Verified profiles, protected workflows, and reputation built from real completed work.</p></div><div><MessageCircle className="h-8 w-8 text-cyan-300" /><h2 className="mt-5 text-2xl font-bold">Built for collaboration</h2><p className="mt-3 text-sm leading-6 text-slate-300">Keep conversations, milestones, submissions, and feedback close to the work.</p></div><div><Search className="h-8 w-8 text-cyan-300" /><h2 className="mt-5 text-2xl font-bold">Built for discovery</h2><p className="mt-3 text-sm leading-6 text-slate-300">Search, matching, and recommendations help you find possibilities faster, with reasons you can understand.</p></div></div></section><section className="mx-auto max-w-7xl px-4 py-20 text-center sm:px-6 lg:px-8"><h2 className="text-3xl font-bold text-slate-900">Ready to make the next move?</h2><div className="mt-7 flex flex-wrap justify-center gap-3"><Link to="/register"><Button size="lg">Create your account <ArrowRight className="h-4 w-4" /></Button></Link><Link to="/services" className="inline-flex items-center gap-2 rounded-lg border border-brand-200 px-6 py-3 text-base font-medium text-brand-700 hover:bg-brand-50">Browse services <Check className="h-4 w-4" /></Link></div></section></div>; }
