import { Router } from 'express';
import mongoose from 'mongoose';
import { config } from '../config/index.js';
import { metricsSnapshot } from '../config/metrics.js';
const router = Router();
router.get('/health/live', (_req, res) => res.json({ success: true, status: 'alive' }));
router.get('/health/ready', (_req, res) => { const ready = mongoose.connection.readyState === 1; res.status(ready ? 200 : 503).json({ success: ready, status: ready ? 'ready' : 'not_ready' }); });
router.get('/health/dependencies', (_req, res) => res.json({ success: true, data: { mongodb: mongoose.connection.readyState === 1 ? 'up' : 'down', payment: config.payment.provider, email: config.email.smtpHost ? 'configured' : 'console', ai: config.ai.provider } }));
router.get('/health/metrics', (_req, res) => res.json({ success: true, data: metricsSnapshot() }));
export default router;
