import { Router } from 'express';
import { requireAuth } from '../middlewares/auth.js';
import { ApiError } from '../utils/ApiError.js';
import { validate } from '../middlewares/validate.js';
import { virtualCardController as c } from '../controllers/virtualCard.controller.js';
import { reload } from '../validators/virtualCard.validators.js';

const router = Router();
const requireDeveloperCard = (req, _res, next) => req.user?.hasRole('freelancer') ? next() : next(new ApiError(403, 'Virtual card information is available only to developers.', 'DEVELOPER_CARD_ACCESS_REQUIRED'));
router.get('/cards/me', requireAuth, c.me);
router.post('/cards/create', requireAuth, c.create);
router.post('/cards/activate', requireAuth, requireDeveloperCard, c.activate);
router.post('/cards/freeze', requireAuth, c.freeze);
router.post('/cards/unfreeze', requireAuth, c.unfreeze);
router.get('/cards/me/transactions', requireAuth, c.transactions);
router.get('/wallet/me', requireAuth, c.wallet);
router.get('/wallet/ledger', requireAuth, c.transactions);
router.post('/wallet/reload', requireAuth, requireDeveloperCard, validate(reload), c.reload);
router.get('/developers/me/eligibility', requireAuth, requireDeveloperCard, c.eligibility);
export default router;
