import { Router } from 'express';
import { requireAuth } from '../middlewares/auth.js';
import { ApiError } from '../utils/ApiError.js';
import { validate } from '../middlewares/validate.js';
import { virtualCardController as c } from '../controllers/virtualCard.controller.js';
import { reload } from '../validators/virtualCard.validators.js';

const router = Router();
const requireDeveloperCard = (req, _res, next) => req.user?.hasRole('freelancer') ? next() : next(new ApiError(403, 'Virtual card information is available only to developers.', 'DEVELOPER_CARD_ACCESS_REQUIRED'));
router.use(requireAuth, requireDeveloperCard);
router.get('/cards/me', c.me);
router.post('/cards/create', c.create);
router.post('/cards/activate', c.activate);
router.post('/cards/freeze', c.freeze);
router.post('/cards/unfreeze', c.unfreeze);
router.get('/cards/me/transactions', c.transactions);
router.get('/wallet/me', c.wallet);
router.get('/wallet/ledger', c.transactions);
router.post('/wallet/reload', validate(reload), c.reload);
router.get('/developers/me/eligibility', c.eligibility);
export default router;
