import crypto from 'node:crypto';
import { Agency } from '../models/Agency.js';
import { AgencyMembership } from '../models/AgencyMembership.js';
import { AgencyInvitation } from '../models/AgencyInvitation.js';
import { User } from '../models/User.js';
import { Notification } from '../models/Notification.js';
import { ApiError } from '../utils/ApiError.js';
import { AGENCY_ROLES } from '../config/constants.js';
const id = (v) => String(v);
const slugify = (s) => String(s).toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 70);
const hash = (s) => crypto.createHash('sha256').update(s).digest('hex');
export async function getMembership(userId, agencyId) { const membership = await AgencyMembership.findOne({ agency: agencyId, user: userId, status: 'active' }); if (!membership) throw ApiError.forbidden('You are not an active agency member'); return membership; }
export function canManage(membership) { return [AGENCY_ROLES.OWNER, AGENCY_ROLES.ADMIN].includes(membership.role); }
export const agencyService = {
  async create(user, body) { let slug = slugify(body.name); if (await Agency.exists({ slug })) slug = `${slug}-${crypto.randomBytes(3).toString('hex')}`; const agency = await Agency.create({ ...body, slug, owner: user._id, members: [user._id] }); await AgencyMembership.create({ agency: agency._id, user: user._id, role: AGENCY_ROLES.OWNER, status: 'active', joinedAt: new Date() }); return agency; },
  async list(query = {}) { const filter = { status: 'active', visibility: 'public' }; if (query.q) filter.$text = { $search: query.q }; return Agency.find(filter).sort(query.q ? { score: { $meta: 'textScore' } } : { createdAt: -1 }).limit(30).populate('owner', 'name avatar'); },
  async getPublic(slug) { const agency = await Agency.findOne({ slug, status: 'active', visibility: { $in: ['public', 'unlisted'] } }).populate('owner', 'name avatar').populate('members', 'name avatar role'); if (!agency) throw ApiError.notFound('Agency not found'); return agency; },
  async getForMember(user, agencyId) { const membership = await getMembership(user._id, agencyId); const agency = await Agency.findById(agencyId).populate('members', 'name avatar role'); if (!agency) throw ApiError.notFound('Agency not found'); return { agency, membership }; },
  async getForMemberBySlug(user, slug) { const agency = await Agency.findOne({ slug }); if (!agency) throw ApiError.notFound('Agency not found'); return this.getForMember(user, agency._id); },
  async update(user, agencyId, body) { const { agency, membership } = await this.getForMember(user, agencyId); if (!canManage(membership)) throw ApiError.forbidden('Agency management permission required'); for (const key of ['name', 'logo', 'coverImage', 'tagline', 'overview', 'category', 'subcategories', 'skills', 'portfolio', 'visibility', 'status']) if (body[key] !== undefined) agency[key] = body[key]; await agency.save(); return agency; },
  async invite(user, agencyId, body) { const { agency, membership } = await this.getForMember(user, agencyId); if (!canManage(membership)) throw ApiError.forbidden('Only owners and admins can invite members'); const invitee = body.email ? await User.findOne({ email: body.email.toLowerCase() }) : null; if (invitee && await AgencyMembership.exists({ agency: agency._id, user: invitee._id, status: 'active' })) throw ApiError.conflict('User is already a member'); const token = crypto.randomBytes(24).toString('hex'); const invitation = await AgencyInvitation.create({ agency: agency._id, email: body.email, invitee: invitee?._id, role: body.role || AGENCY_ROLES.MEMBER, invitedBy: user._id, tokenHash: hash(token), expiresAt: new Date(Date.now() + 7 * 86400000) }); if (invitee) await Notification.create({ recipient: invitee._id, sender: user._id, type: 'AGENCY_INVITATION' }); return { invitation, token }; },
  async members(user, agencyId) { await getMembership(user._id, agencyId); return AgencyMembership.find({ agency: agencyId, status: { $in: ['active', 'invited'] } }).populate('user', 'name email avatar role status'); },
  async accept(user, invitationId, token) { const invitation = await AgencyInvitation.findOne({ _id: invitationId, tokenHash: hash(token), status: 'pending' }); if (!invitation || invitation.expiresAt < new Date()) throw ApiError.badRequest('Invitation is invalid or expired'); if (invitation.invitee && id(invitation.invitee) !== id(user._id)) throw ApiError.forbidden('This invitation belongs to another user'); const membership = await AgencyMembership.findOneAndUpdate({ agency: invitation.agency, user: user._id }, { agency: invitation.agency, user: user._id, role: invitation.role, status: 'active', invitedBy: invitation.invitedBy, joinedAt: new Date() }, { upsert: true, new: true }); await Agency.updateOne({ _id: invitation.agency }, { $addToSet: { members: user._id } }); invitation.status = 'accepted'; await invitation.save(); return membership; },
  async decline(user, invitationId) { const invitation = await AgencyInvitation.findOne({ _id: invitationId, invitee: user._id, status: 'pending' }); if (!invitation) throw ApiError.notFound('Invitation not found'); invitation.status = 'declined'; await invitation.save(); return invitation; },
  async invitations(user) { return AgencyInvitation.find({ $or: [{ invitee: user._id }, { email: user.email }], status: 'pending', expiresAt: { $gt: new Date() } }).populate('agency', 'name slug logo').sort({ createdAt: -1 }); },
};
