import crypto from 'node:crypto';
import { Contract } from '../models/Contract.js';
import { ActiveTimer } from '../models/ActiveTimer.js';
import { TimeEntry } from '../models/TimeEntry.js';
import { BillingPeriod } from '../models/BillingPeriod.js';
import { HourlyInvoice } from '../models/HourlyInvoice.js';
import { ApiError } from '../utils/ApiError.js';
const uid = (u) => u._id || u.id;
const amount = (minutes, rate) => Math.round((minutes * rate / 60) * 100) / 100;
const getContract = async (user, id) => { const c = await Contract.findById(id); if (!c) throw ApiError.notFound('Contract not found'); if (![String(c.client), String(c.freelancer)].includes(String(uid(user)))) throw ApiError.forbidden('Not a contract participant'); if (c.type !== 'hourly') throw ApiError.badRequest('This is not an hourly contract'); return c; };
const freelancer = async (user, id) => { const c = await getContract(user, id); if (String(c.freelancer) !== String(uid(user))) throw ApiError.forbidden('Only the freelancer can track time'); return c; };
export const hourlyService = {
  summary: async (u, id) => { const c = await getContract(u, id); const entries = await TimeEntry.find({ contract: c._id, deletedAt: null }).sort({ startedAt: -1 }).limit(100); return { contract: c, activeTimer: await ActiveTimer.findOne({ contract: c._id, user: uid(u), status: { $in: ['running', 'paused'] } }), entries, totalMinutes: entries.reduce((n, e) => n + e.billableMinutes, 0) }; },
  start: async (u, id, body = {}) => { const c = await freelancer(u, id); if (c.status !== 'active' || !c.trackedTimeAllowed) throw ApiError.badRequest('Time tracking is not available'); if (await ActiveTimer.findOne({ user: uid(u), status: 'running' })) throw ApiError.conflict('You already have an active timer'); const now = new Date(); return ActiveTimer.create({ user: uid(u), contract: c._id, startedAt: now, lastHeartbeatAt: now, deviceId: body.deviceId, sessionId: crypto.randomUUID() }); },
  heartbeat: async (u, timerId) => { const t = await ActiveTimer.findOneAndUpdate({ _id: timerId, user: uid(u), status: 'running' }, { lastHeartbeatAt: new Date() }, { new: true }); if (!t) throw ApiError.notFound('Active timer not found'); return t; },
  stop: async (u, timerId, body = {}) => { const t = await ActiveTimer.findOne({ _id: timerId, user: uid(u), status: { $in: ['running', 'paused'] } }); if (!t) throw ApiError.notFound('Active timer not found'); const c = await freelancer(u, t.contract); const end = new Date(); const duration = Math.max(1, Math.floor((end - t.startedAt) / 60000)); const step = c.roundingInterval || 1; const billable = Math.max(c.minimumBillableMinutes || 1, Math.ceil(duration / step) * step); const entry = await TimeEntry.create({ contract: c._id, project: body.project, user: uid(u), startedAt: t.startedAt, endedAt: end, durationMinutes: duration, billableMinutes: billable, hourlyRate: c.hourlyRate ?? c.rate, amount: amount(billable, c.hourlyRate ?? c.rate), description: body.description || 'Tracked work', source: 'timer', timezone: c.billingTimezone, idempotencyKey: body.idempotencyKey }); await ActiveTimer.findByIdAndUpdate(t._id, { status: 'stopped', lastHeartbeatAt: end, accumulatedMinutes: billable }); return entry; },
  createEntry: async (u, id, body = {}) => { const c = await freelancer(u, id); if (!c.manualTimeAllowed) throw ApiError.forbidden('Manual time is disabled'); const start = new Date(body.startedAt); const end = new Date(body.endedAt); const duration = Math.floor((end - start) / 60000); if (!Number.isFinite(duration) || duration < 1 || !body.description) throw ApiError.badRequest('Valid times and a description are required'); const step = c.roundingInterval || 1; const billable = Math.max(c.minimumBillableMinutes || 1, Math.ceil(duration / step) * step); return TimeEntry.create({ contract: c._id, project: body.project, user: uid(u), startedAt: start, endedAt: end, durationMinutes: duration, billableMinutes: billable, hourlyRate: c.hourlyRate ?? c.rate, amount: amount(billable, c.hourlyRate ?? c.rate), description: body.description, source: 'manual', timezone: c.billingTimezone, idempotencyKey: body.idempotencyKey }); },
  entries: async (u, id) => { const c = await getContract(u, id); return TimeEntry.find({ contract: c._id, deletedAt: null }).sort({ startedAt: -1 }).limit(100); },
  removeEntry: async (u, entryId) => { const e = await TimeEntry.findById(entryId); if (!e || String(e.user) !== String(uid(u))) throw ApiError.notFound('Time entry not found'); if (e.status === 'approved') throw ApiError.conflict('Approved time cannot be deleted'); e.deletedAt = new Date(); e.deletedBy = uid(u); e.status = 'deleted'; return e.save(); },
  generateInvoice: async (u, id, startValue, endValue) => { const c = await freelancer(u, id); const start = new Date(startValue); const end = new Date(endValue); if (Number.isNaN(start.valueOf()) || Number.isNaN(end.valueOf()) || end <= start) throw ApiError.badRequest('Invalid billing period'); const entries = await TimeEntry.find({ contract: c._id, deletedAt: null, startedAt: { $gte: start, $lt: end } }); const minutes = entries.reduce((n, e) => n + e.billableMinutes, 0); const subtotal = amount(minutes, c.hourlyRate ?? c.rate); const period = await BillingPeriod.findOneAndUpdate({ contract: c._id, periodStart: start }, { $setOnInsert: { contract: c._id, client: c.client, freelancer: c.freelancer, periodStart: start, periodEnd: end }, $set: { totalMinutes: entries.reduce((n, e) => n + e.durationMinutes, 0), billableMinutes: minutes, subtotal, status: 'locked', lockedAt: new Date() } }, { upsert: true, new: true }); return HourlyInvoice.findOneAndUpdate({ billingPeriod: period._id }, { $setOnInsert: { invoiceNumber: `H-${Date.now()}`, contract: c._id, billingPeriod: period._id, client: c.client, freelancer: c.freelancer, lineItems: entries.map((e) => ({ date: e.startedAt, description: e.description, minutes: e.billableMinutes, hours: e.billableMinutes / 60, rate: e.hourlyRate, amount: e.amount })), subtotal, platformFee: 0, freelancerAmount: subtotal, currency: c.currency } }, { upsert: true, new: true }); }
};
