import crypto from 'node:crypto';
import { Job } from '../models/Job.js';
import { Proposal } from '../models/Proposal.js';
import { FreelancerProfile } from '../models/FreelancerProfile.js';
import { Reputation } from '../models/Reputation.js';
import { MatchResult } from '../models/MatchResult.js';
import { AIProcessing } from '../models/AIProcessing.js';
import { ApiError } from '../utils/ApiError.js';
const synonyms = { 'next.js': ['react', 'javascript'], node: ['node.js'], nodejs: ['node.js'], frontend: ['react', 'vue', 'angular'], backend: ['node.js', 'python', 'java'], aws: ['docker', 'linux'] };
const norm = (s) => String(s || '').toLowerCase().replace(/[^a-z0-9+#.]/g, '');
const expanded = (s) => new Set([norm(s), ...(synonyms[norm(s)] || [])]);
const sourceHash = (job, proposal, profile) => crypto.createHash('sha256').update(JSON.stringify({ job: job.updatedAt, proposal: proposal.updatedAt, profile: profile?.updatedAt })).digest('hex');
function requirements(job) { const text = `${job.title} ${job.description} ${(job.skills || []).join(' ')}`.toLowerCase(); const requiredSkills = job.skills?.length ? job.skills : ['javascript', 'communication'].filter((x) => text.includes(x)); const preferredSkills = ['docker', 'aws', 'typescript', 'testing'].filter((x) => text.includes(x) && !requiredSkills.some((r) => norm(r) === x)); return { requiredSkills, preferredSkills, minimumYears: job.experienceLevel === 'expert' ? 5 : job.experienceLevel === 'intermediate' ? 2 : 0, analyzedAt: new Date() }; }
function overlap(required, mine) { const own = new Set((mine || []).flatMap((s) => [...expanded(s)])); return { matched: required.filter((s) => [...expanded(s)].some((x) => own.has(x))), missing: required.filter((s) => ![...expanded(s)].some((x) => own.has(x))) }; }
export const matchingService = {
  async analyzeJob(user, jobId) { const job = await Job.findById(jobId); if (!job) throw ApiError.notFound('Job not found'); if (String(job.client) !== String(user._id)) throw ApiError.forbidden('Only the job owner can analyze this job'); const req = requirements(job); job.aiRequirements = req; job.aiQualityScore = Math.min(100, 50 + Math.min(30, req.requiredSkills.length * 6) + (job.description.length > 300 ? 20 : 5)); job.aiAnalysisUpdatedAt = new Date(); await job.save(); return { requirements: req, qualityScore: job.aiQualityScore, suggestions: job.description.length < 300 ? ['Add clearer deliverables and acceptance criteria.'] : [] }; },
  async matchJob(user, jobId) { const job = await Job.findById(jobId); if (!job || String(job.client) !== String(user._id)) throw ApiError.notFound('Job not found'); const proposals = await Proposal.find({ job: job._id, status: { $in: ['submitted', 'shortlisted'] } }); const results = []; const req = job.aiRequirements?.requiredSkills?.length ? job.aiRequirements : requirements(job); for (const proposal of proposals) { const profile = await FreelancerProfile.findOne({ user: proposal.freelancer }); const reputation = await Reputation.findOne({ user: proposal.freelancer }); const required = overlap(req.requiredSkills, profile?.skills); const preferred = overlap(req.preferredSkills, profile?.skills); const years = profile?.experience?.length ? Math.min(10, profile.experience.length * 2) : 0; const experienceMatch = req.minimumYears ? Math.min(100, (years / req.minimumYears) * 100) : 100; const proposalText = (proposal.coverLetter || '').toLowerCase(); const proposalMatch = req.requiredSkills.length ? req.requiredSkills.filter((s) => proposalText.includes(String(s).toLowerCase())).length / req.requiredSkills.length * 100 : 50; const reputationScore = reputation?.averageRating ? reputation.averageRating / 5 * 100 : 50; const score = Math.round(required.matched.length / Math.max(1, req.requiredSkills.length) * 35 + experienceMatch * .2 + Math.min(100, (required.matched.length + preferred.matched.length) / Math.max(1, req.requiredSkills.length + req.preferredSkills.length) * 15) + proposalMatch * .1 + reputationScore * .05 + (profile?.availability && profile.availability !== 'not_available' ? 5 : 0)); const result = { job: job._id, freelancer: proposal.freelancer, proposal: proposal._id, matchScore: Math.min(100, score), confidence: Math.min(1, .5 + required.matched.length / Math.max(1, req.requiredSkills.length) * .5), matchedSkills: [...required.matched, ...preferred.matched], missingSkills: [...required.missing, ...preferred.missing], experienceMatch: Math.round(experienceMatch), projectMatch: Math.min(100, (profile?.portfolio?.length || 0) * 20), reputationSignals: { rating: reputation?.averageRating || 0, reviews: reputation?.reviewCount || 0 }, explanation: { strengths: required.matched.map((s) => `${s} matches a required skill`), gaps: required.missing.map((s) => `No profile evidence for ${s}`), disclaimer: 'AI-assisted recommendation only. The client makes the hiring decision.' }, sourceHash: sourceHash(job, proposal, profile) }; const saved = await MatchResult.findOneAndUpdate({ job: job._id, proposal: proposal._id }, result, { upsert: true, new: true, setDefaultsOnInsert: true }); results.push(saved); } return results.sort((a, b) => b.matchScore - a.matchScore); },
  async listMatches(user, jobId) { const job = await Job.findById(jobId); if (!job || String(job.client) !== String(user._id)) throw ApiError.notFound('Job not found'); return MatchResult.find({ job: job._id }).sort({ matchScore: -1 }).populate('freelancer', 'name avatar').populate('proposal', 'bid estimatedDays status'); },
};
